development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: walter_bishop
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: walter_bishop_test
  username: root
  password:
